import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Providers from './provider';
import { SessionProvider } from '@/providers/sessionProvider';
import { GradientLayout } from '@/components/gradientLayout';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        cz-shortcut-listen="true"
      >
        <Providers>
          <SessionProvider>
            <div className="flex w-full bg-background min-h-screen items-center justify-center">
              {/* <GradientLayout> */}
              {children}
              {/* <Toaster /> */}
              {/* </GradientLayout> */}
            </div>
          </SessionProvider>
        </Providers>
      </body>
    </html>
  );
}
